export const productsListPage = [
  {
    name: "Rhenacret Nivelador 2000",
    subtitle: "Mortero Autonivelante Cementicio",
    desc: "Rhenacret Nivelador 2000 es un mortero autonivelante diseñado para la nivelación y afinado de pisos interiores como losas y sobrelosas de concreto y radieres. Su formulación aporta consistencia plástica y reológica permitiendo una óptima trabajabilidad y terminación final.",
    features: [
      { id: 1, feature: "Autonivelante" },
      { id: 2, feature: "Fácil preparación y colocación." },
      { id: 3, feature: "Transitable a partir de las 4 horas en adelante." },
      { id: 4, feature: "Alta estabilidad dimensional y durabilidad." },
      { id: 5, feature: "Acabado liso y fino acompañado de alta resistencia final." },
      { id: 6, feature: "Alta trabajabilidad y rendimiento." },
      {
        id: 7, feature: "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      },
      { id: 8, feature: "No sufre retracciones hasta el espesor máximo indicado." },
      { id: 9, feature: "Uso exclusivo para superficies interiores." },
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/rhenacret_nivelador_img1.png?alt=media&token=e7ae47e9-06b6-4dcb-91bb-803fc7828c92",
    price: "$16.500",
    url: "/product-details-4",
  },
  {
    name: "Rhenacret TOP RTU",
    subtitle: "Promotor de Adherencia Listo para Uso",
    desc: "Rhenacret TOP RTU es una emulsión elastomérica que permite mejorar la trabajabilidad, adherencia, flexibilidad e impermeabilidad de los morteros. Forma parte del sistema de productos Rhenatec para la nivelación de pisos, actuando como matapolvo, promotor de adherencia y sellador de superficies.",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/rhenatec_top_img2.png?alt=media&token=e239c98a-5e11-4f7e-b303-1b114860b58c",
    price: "$16.500",
    url: "/product-details-5",
  },
  {
    name: "Rhenapur Espuma PU Expansiva",
    subtitle: "Espuma de poliuretano",
    desc: "Rhenapur Espuma PU Autoexpandible es una espuma de poliuretano de color amarillo suave monocomponente, ideal para rellenos de cavidades, aislación térmica y acústica, con afinidad a una gran variedad de materiales de construcción.",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/rhenapur_espuma_img3.png?alt=media&token=0bca99ff-74d9-4542-883d-ee50521b97f9",
    price: "$16.500",
    url: "/product-details-6",
  },
  {
    name: "Ultrabond Eco V4 Evolution",
    subtitle: "Adhesivo Vinílico | 4 Lvt (14 Kg)",
    desc: "Adhesivo acrílico universal en dispersión acuosa, sin disolventes, con un tiempo abierto prolongado. Para la colocación de pavimentos de goma, PVC, vinílicos, poliolefínicos, linóleo.",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/ultrabond_eco_img4.png?alt=media&token=b1f9cf17-6d80-4333-81cc-88398725b0c8",
    price: "$16.500",
    url: "/product-details-7",
  },
  {
    name: "Primer G",
    subtitle: "Promotor De Adherencia Universal | (10 Kg)",
    desc: "Listo para usar tanto en interiores como en exteriores, en paredes y pavimentos. Mejora la adherencia de enlucidos y adhesivos para cerámica en superficies no absorbentes como porcelanatos, metal, estuco, yeso, incluso vidrio. Secado rápido y tiempo de uso extendido. Monocomponente y fácil aplicación con brocha o rodillo.",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/primer_g_img5.png?alt=media&token=56877c02-76fa-4f3b-b426-706f37f5a393",
    price: "$16.500",
    url: "/product-details-8",
  },
  {
    name: "Eco Prim Grip Plus",
    subtitle: "Promotor De Adherencia Universal | (10 Kg)",
    desc: "Listo para usar tanto en interiores como en exteriores, en paredes y pavimentos. Mejora la adherencia de enlucidos y adhesivos para cerámica en superficies no absorbentes como porcelanatos, metal, estuco, yeso, incluso vidrio. Secado rápido y tiempo de uso extendido. Monocomponente y fácil aplicación con brocha o rodillo.",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/mapei_grip_plus_img6.png?alt=media&token=f952b51b-b802-484a-9ef9-40cd2a1d6e50",
    price: "$106.900",
    url: "/product-details-9",
  },
  {
    name: "Ultraplan Contract 3-40",
    subtitle: "Mortero Autonivelante",
    desc: "Mortero autonivelante altamente fluido, de secado rápido para espesores de 3 a 40 mm con alta resistencia a la compresión (28 MPa). Para nivelación de pisos previo a la instalación de revestimientos: pisos vinilicos pegados, de caucho madera o pisos flotantes (SPC, LVT).",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/mapei_ultraplan_contact_img7.png?alt=media&token=fee50e15-e7bc-4c78-9a03-2c74e17e312d",
    price: "$17.900",
    url: "/product-details-10",
  },
  {
    name: "Planiprep Fast Track",
    subtitle: "Retape De Piso (4 Kg)",
    desc: "Mortero cementicio de retape y parchado tixotrópico de textura fina y secado ultrarrápido. Adecuado para afinado, retape de pisos y muros de hormigón nuevo y existente, para espesores de 0 a 3 mm, preparación de superficies previa a la instalación de todo tipo de revestimientos de pisos y muros. Se puede instalar el revestimiento muy rápidamente (2 horas), incluyendo vinilos, caucho y textiles.",
    features: [
      "Autonivelante",
      "Fácil preparación y colocación.",
      "Transitable a partir de las 4 horas en adelante.",
      "Alta estabilidad dimensional y durabilidad.",
      "Acabado liso y fino acompañado de alta resistencia final.",
      "Alta trabajabilidad y rendimiento.",
      "Colocación desde 3 hasta 30 mm. de espesor en una sola aplicación.",
      "No sufre retracciones hasta el espesor máximo indicado.",
      "Uso exclusivo para superficies interiores.",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/login-huellitas.appspot.com/o/mapei_planiprep_fast_img8.png?alt=media&token=9ffe3b19-21a6-4ad9-9a98-0fc17af6010e",
    price: "$14.990",
    url: "/product-details-11",
  },
];
