export const projects = [
  {
    name: "Mathiesen",
    mt2: "1.135",
    duration: "15 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante en toda la superficie, instalación de alfombra y Piso Vinílico LVT.",
    thumbnail: "/assets/images/projects/mathiensen/thumbnail.png",
    images: [
      "/assets/images/projects/mathiensen/mathiensen_01.png",
      "/assets/images/projects/mathiensen/mathiensen_02.png",
      "/assets/images/projects/mathiensen/mathiensen_03.png",
      "/assets/images/projects/mathiensen/mathiensen_04.png",
      "/assets/images/projects/mathiensen/mathiensen_05.png",
      "/assets/images/projects/mathiensen/mathiensen_06.png",
      "/assets/images/projects/mathiensen/mathiensen_07.png",
      "/assets/images/projects/mathiensen/mathiensen_08.png",
    ],
  },
  {
    name: "Patio Foster",
    mt2: "300",
    duration: "5 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante en toda la superficie a instalar pavimentos. Instalación de Piso Vinílico.",
    thumbnail: "/assets/images/projects/patioposter/patio_poster_thumbnail.png",
    images: [
      "/assets/images/projects/patioposter/patio_poster_01.png",
      "/assets/images/projects/patioposter/patio_poster_02.png",
      "/assets/images/projects/patioposter/patio_poster_03.png",
      "/assets/images/projects/patioposter/patio_poster_04.png",
      "/assets/images/projects/patioposter/patio_poster_05.png",
      "/assets/images/projects/patioposter/patio_poster_06.png",
      "/assets/images/projects/patioposter/patio_poster_07.png",
      "/assets/images/projects/patioposter/patio_poster_08.png",
      "/assets/images/projects/patioposter/patio_poster_09.png",
      "/assets/images/projects/patioposter/patio_poster_10.png",
      "/assets/images/projects/patioposter/patio_poster_11.png",
    ],
  },
  {
    name: "Cajon del Maipo",
    mt2: "1000",
    duration: "1 día",
    year: "2022",
    description: "Aplicación de Autonivelante.",
    thumbnail:
      "/assets/images/projects/cajondelmaipo/cajon_maipo_thumbnail.png",
    images: [
      "/assets/images/projects/cajondelmaipo/cajon_maipo_01.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_02.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_03.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_04.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_05.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_06.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_07.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_08.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_09.png",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_10.png",
    ],
  },
  {
    name: "CMaster",
    mt2: "200",
    duration: "5 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante e instalación de piso Vinílico en Rollo.",
    thumbnail: "/assets/images/projects/cmaster/cmaster_thumbnail.png",
    images: [
      "/assets/images/projects/cmaster/cmaster_01.png",
      "/assets/images/projects/cmaster/cmaster_02.png",
      "/assets/images/projects/cmaster/cmaster_03.png",
      "/assets/images/projects/cmaster/cmaster_04.png",
      "/assets/images/projects/cmaster/cmaster_05.png",
      "/assets/images/projects/cmaster/cmaster_06.png",
      "/assets/images/projects/cmaster/cmaster_07.png",
      "/assets/images/projects/cmaster/cmaster_08.png",
      "/assets/images/projects/cmaster/cmaster_09.png",
      "/assets/images/projects/cmaster/cmaster_10.png",
      "/assets/images/projects/cmaster/cmaster_11.png",
      "/assets/images/projects/cmaster/cmaster_12.png",
      "/assets/images/projects/cmaster/cmaster_13.png",
    ],
  },
  {
    name: "Fosforo Estudio H",
    mt2: "531",
    duration: "5 días",
    year: "2022",
    description: "Instalación de Piso Vinílico LVT.",
    thumbnail:
      "/assets/images/projects/fosforoestudio/fosforo_estudio_thumbnail.png",
    images: [
      "/assets/images/projects/fosforoestudio/fosforo_estudio_01.png",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_02.png",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_03.png",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_04.png",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_05.png",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_06.png",
    ],
  },
  {
    name: "Oficina Casbro",
    mt2: "150",
    duration: "5 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante. Instalación de Piso Vinílico LVT e Instalación de Alfombra.",
    thumbnail: "/assets/images/projects/oficinacasbro/casbro_thumbnail.png",
    images: [
      "/assets/images/projects/oficinacasbro/casbro_01.png",
      "/assets/images/projects/oficinacasbro/casbro_02.png",
      "/assets/images/projects/oficinacasbro/casbro_03.png",
      "/assets/images/projects/oficinacasbro/casbro_04.png",
      "/assets/images/projects/oficinacasbro/casbro_05.png",
      "/assets/images/projects/oficinacasbro/casbro_06.png",
      "/assets/images/projects/oficinacasbro/casbro_07.png",
    ],
  },
  {
    name: "Pichilemu",
    mt2: "70",
    duration: "1 día",
    year: "2023",
    description: "Aplicación de Autonivelante.",
    thumbnail: "/assets/images/projects/pichilemu/pichilemu_thumbnail.png",
    images: [
      "/assets/images/projects/pichilemu/pichilemu_01.png",
      "/assets/images/projects/pichilemu/pichilemu_02.png",
      "/assets/images/projects/pichilemu/pichilemu_03.png",
      "/assets/images/projects/pichilemu/pichilemu_04.png",
      "/assets/images/projects/pichilemu/pichilemu_05.png",
    ],
  },
  {
    name: "San Antonio",
    mt2: "500",
    duration: "3 días",
    year: "2022",
    description: "Aplicación e Instalación de Autonivelante.",
    thumbnail: "/assets/images/projects/sanantonio/sanantonio_thumbnail.png",
    images: [
      "/assets/images/projects/sanantonio/sanantonio_01.png",
      "/assets/images/projects/sanantonio/sanantonio_02.png",
      "/assets/images/projects/sanantonio/sanantonio_03.png",
      "/assets/images/projects/sanantonio/sanantonio_04.png",
      "/assets/images/projects/sanantonio/sanantonio_05.png",
    ],
  },
];
